### ISSUE TITLE
CSS dev tooling

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#108]
Check if useful:

https://blog.logrocket.com/firefox-devtools-for-css-authors-1511f41d1e3

https://developer.mozilla.org/en-US/docs/Tools/Page_Inspector/How_to/Examine_and_edit_CSS

**Comment by alexTrod** [comment]
The second link could be mentioned in the lecture as there is no mention (or very little) to CSS dev tools. 
The first link covers features beyond the scope of the course as well as interesting features (e.g. fonts, responsive design mode, grid, filter). Therefore, it could be mentioned as a recommended reading.

**Comment by chauff** [comment]
done
