### ISSUE TITLE
Frontend masters 2019

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#118]
https://frontendmasters.com/books/front-end-handbook/2019/#1

an additional source of information or too much / too broad / too confusing?

**Comment by lyrakisk** [comment]
Although this guide is excellent and provides a lot of useful information about the industry I think it goes a bit beyond the scope of this course. Maybe we could at it as extra reading material on lecture 6 or 7?

**Comment by azqa** [comment]
There are definitely a lot of links to good resources, but it would require some effort to integrate it properly in the course content at this time. Agreed with the suggestion to put it as extra reading material.
