### ISSUE TITLE
Async JS guide

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#122]
https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Asynchronous - check if it is worth pointing to it (intro material to timeouts, etc.)

**Comment by lyrakisk** [comment]
I believe it is worth pointing to this page. It has a lot of nice a examples and it explains async JavaScript in a way suitable for everyone that has basic computer programming experience. The first 3 guides contained in the page should be enough for Q2 students.

Should I put it as a link to the JS lecture? Or as a link to required/recommended reading material? @chauff @azqa

**Comment by azqa** [comment]
I would put it after ajax is introduced, and say in a few lines what async JS is and that here's a nice resource with lots of examples. I think it will get lost in recommended readings.
