### ISSUE TITLE
Telnet exercises in A1 - check them (http vs https issue)

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#134]

**Comment by chauff** [comment]
Telnet only works with http connections, every year more and more websites switch to https and then this assignment breaks. Ideally we avoid switching to openSSL (a bit more complex to set up and run), so we need to update the assignment to ensure that our chosen website remains on http.

**Comment by radostefanov** [comment]
Both `weer.nl` and `httpbin.org` still support HTTP requests (and all of their subdirectories used in the assignment). `httpbin.org` supports HTTPS, but it doesn't do redirects to HTTPS for requests to HTTP.
However, in Lecture 1, all examples with `telnet microsoft.com 80` don't work, as `microsoft.com` returns a 302 error with redirect location set to `https://...`. Therefore we would need to use a different website
