### ISSUE TITLE
CSS cache-control in depth

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#137]
https://csswizardry.com/2019/03/cache-control-for-civilians/

check utility

**Comment by radostefanov** [comment]
The link contains mostly details about all possible parameters of Cache-Control, which is great, but i don't think that is so important for the CSS part, and Cache-Control is also already explained in the first lecture. One thing useful might be to add a few lines at the end of the CSS lecture about cleaning the cache of css files (cache busting)
