### ISSUE TITLE
1st/3rd party cookies (Facebook)

### ISSUE THREAD

**Issue by chauff** [chauff/Web-Teaching#190]
https://threadreaderapp.com/thread/1199817699116736512.html

**Comment by azqa** [comment]
Interesting article! Sub-topics that you can consider:
- Differences between 1st and 3rd party cookies (e.g. why choose one over the other)
- Privacy implications of 1st/3rd party cookies (how trackers work, how to protect privacy)

**Comment by chauff** [comment]
done
