### ISSUE TITLE
Assignment4

### ISSUE THREAD

**Issue by Andyshome** [chauff/Web-Teaching#197]
It seems www.weer.nl/regenradar/nederland this website does not work, it returns 404 all the time. Would you mind to fix that? Thanks!

**Comment by chauff** [comment]
Thanks for the pointer, the change happened around New Year's. We will have an update tonight!

**Comment by Andyshome** [comment]
Thank you !

**Comment by chauff** [comment]
Assignment four has been updated. Exercise 1 required a change, the remaining exercises are unaffected.
