### ISSUE TITLE
Large repository size 

### ISSUE THREAD

**Issue by ValentijnvdBeek** [chauff/Web-Teaching#200]
# Explanation
The size of this repository is currently at around 550MiB which about the same as a full [Windows ME](https://en.wikipedia.org/wiki/Windows_Me#System_requirements) install plus [Rollercoaster Tycoon](https://www.game-debate.com/games/index.php?g_id=1891&game=RollerCoaster%20Tycoon) and [the original Doom](https://gamesystemrequirements.com/game/doom). It also takes my laptop around [3 minutes](https://gist.github.com/ValentijnvdBeek/a6679d000164bbfec17ad17b8130db33) to be able to do a flesh clone of the repository. Executing [`du -h`](https://gist.github.com/ValentijnvdBeek/d383066999430620ee4f8a36ef7d99aa) seems to indicate that the main cause of this are the generated PDF's (#110) for the slides and the handouts 

This makes since PDFs are binary blobs which can change widely even if the actual change in the source document is very small. This means that for every change the entire file gets committed instead of just the small change as you would expect given Git's normal behavior. Since git stores all possible previous versions of a given file and the fact that PDFs take multiple megabytes this can easily lead to an  unintended explosion in repository size

# Suggested fix
I would suggesting adding *.pdf to the .gitignore and [removing them from the git history](https://robinwinslow.uk/2013/06/11/dont-ever-commit-binary-files-to-git/) as well. For the most part having just the markdown files will be enough since the Github user interface renders them as well. You could also add a Makefile to generate the PDFs or [use a post-checkout git hook ](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks)

For the few PDFs which cannot easily be generated I would recommend putting them on the Brightspace page and linking to them from here since Git just isn't really made for binary files. 

Thanks for your time.

Cheers, 

Valentijn

**Comment by chauff** [comment]
Thanks for the pointers Valentijn! I followed up on it and got the repo down to 100MB.
