### ISSUE TITLE
possibly a minor typo?

### ISSUE THREAD

**Issue by levinwinter** [chauff/Web-Teaching#303]
## Lecture
Which lectures?
* [X] HTTP
* [ ] HTML & design
* [ ] JavaScript
* [ ] Node.js
* [ ] CSS
* [ ] Node.js II
* [ ] Sessions
* [ ] Web security

## What is the issue?
Whilst not being entirely sure, I suspect that the paragraph of the [status codes](https://chauff.github.io/Web-Teaching/http/#status-codes) section contains a small typo. Instead of `https://delft/nl` I would have expected a redirect to `https://delft.nl` (which would match the screenshot of the Firefox Dev Tools in the transcript).

> The status codes `302 Moved Temporarily` and `301 Moved Permanently` indicate that the resource at `http://delft.nl` has been moved elsewhere: first to **`https://delft/nl`** and then to `https://www.delft.nl`. Each time, the Location header tells us the new location.

**Comment by chauff** [comment]
Good catch! Fixed now. Thanks.
