### ISSUE TITLE
incorrect .filter() function?

### ISSUE THREAD

**Issue by levinwinter** [chauff/Web-Teaching#304]
## Lecture
Which lectures?
* [ ] HTTP
* [ ] HTML & design
* [x] JavaScript
* [ ] Node.js
* [ ] CSS
* [ ] Node.js II
* [ ] Sessions
* [ ] Web security

## What is the issue?

In [this](https://chauff.github.io/Web-Teaching/js/#the-keyword-this) section about `this`, the use of the `.filter()` method is explained in a :cookie: paragraph. I suspect that instead of filtering for strings of more than five characters, the given code filters for strings with more than ten characters.

> If we want to only keep those strings of more than **five** characters we use `let arLong = ar.filter(x => x.length > 10)`.

**Comment by chauff** [comment]
Thanks. Fixed.
