### ISSUE TITLE
also update variable name in code snippet comment

### ISSUE THREAD

**Issue by levinwinter** [chauff/Web-Teaching#305]
## Lecture
Which lectures?
* [ ] HTTP
* [ ] HTML & design
* [x] JavaScript
* [ ] Node.js
* [ ] CSS
* [ ] Node.js II
* [ ] Sessions
* [ ] Web security

## What is the issue?

As I am not too sure whether GitHub notifies the author of comments on commits, I am posting this here as well. In essence, when renaming the variable from `h` to `name`, the comment should have been updated as well.

Please see https://github.com/chauff/Web-Teaching/commit/ad43dc7301529c35f3c7db4514e60b807d04c327#r45578812 for further reference.

**Comment by chauff** [comment]
Fixed, thanks.
