### ISSUE TITLE
Imbalanced A-B-C Testing Setup

### ISSUE THREAD

**Issue by levinwinter** [chauff/Web-Teaching#306]
## Lecture
Which lectures?
* [ ] HTTP
* [ ] HTML & design
* [ ] JavaScript
* [ ] Node.js
* [ ] CSS
* [x] Node.js II
* [ ] Sessions
* [ ] Web security

## What is the issue?
In the part on routing, an A-B-C testing setup is provided in which "each handler will be used for about one third of all clients".

```javascript
//A-B-C testing
app.get('/wishlist',
    function(req,res, next){
        if (Math.random() < 0.33) { // change to 0.33 < Math.random()
            return next();
        }
        console.log("Wishlist in schema A returned");
        res.json(wishlist_A);
    },
    function(req,res, next){
        if (Math.random() < 0.5) {
            return next();
        }
        console.log("Wishlist in schema B returned");
        res.json(wishlist_B);
    },
    function(req,res){
        console.log("Wishlist in schema C returned");
        res.json(wishlist_C);
    }
);
```

However, the first `if` condition needs to be inverted in order to achieve an even distribution.

**Comment by chauff** [comment]
Thanks!
