### ISSUE TITLE
Discrepancy Between Code, Text, And Image

### ISSUE THREAD

**Issue by levinwinter** [chauff/Web-Teaching#309]
## Lecture
Which lectures?
* [ ] HTTP
* [ ] HTML & design
* [ ] JavaScript
* [ ] Node.js
* [x] CSS
* [ ] Node.js II
* [ ] Sessions
* [ ] Web security

## What is the issue?

The information in the two bullet points in [this section](https://chauff.github.io/Web-Teaching/css/#bangbang-nth-childx-and-nth-of-typex) neither aligns with the image nor with the given code.

> * the third `<div>` (17 games waiting …) element is the fourth child of its parent `<body>` and thus is rendered with a dashed black border;
> * the fourth `<div>` (2,302 users …) element is the fourth sibling among the group of `<div>` elements and thus rendered with a solid black border.

![image](https://chauff.github.io/Web-Teaching/img/css-pseudo-classes.png)

```html
<!DOCTYPE html>
    <head>
        <style>
            div {
                margin-bottom: 2px;
                padding: 2px;
                white-space: pre;
                font-family: monospace;
            }
            div:nth-child(2n){
                background-color: orchid;
                color: lavender;
            }
            div:nth-child(2n+1){
                background-color: lavender;
                color: orchid;
            }
            div:nth-child(3) {
                border: 1px dashed black;
            }
            div:nth-of-type(3) {
                border: 1px solid black;
            }
        </style>
    </head>

    <body>
        <h1>Game statistics</h1>
        <div>12,567 players registered</div>
        <div>   231 games ongoing</div>
        <div>    17 games waiting for players to join</div>
        <div> 2,302 users are in audience mode</div>
        <div>99.87% server uptime</div>
    </body>
</html>
```

**Comment by chauff** [comment]
Thanks, the explanation is fixed now.
