### ISSUE TITLE
Small spelling mistake

### ISSUE THREAD

**Issue by EMLGaming** [chauff/Web-Teaching#310]
## Lecture
Which lectures?
*  JavaScript

## What is the issue?
https://github.com/chauff/Web-Teaching/blob/master/_lectures/js.md#scoping-hoisting-and-this
First line under "Scoping, hoisting and this" it states: "We now cover three JavaScript principles that often lead to confusion and **log** debugging sessions." the log should be long. 

Further more I would recommend people to watch this playlist https://www.youtube.com/watch?v=4Jk_I-cw4WE&list=PLI_rLWXMqpSl_TqX9bbisW-d7tDqcVvOJ  It goes over all the security subjects in a very clear way and gives you a deeper understanding. In my opinion it is not possible to expect people to complete the OWASP juice shop without having prior security experience. Since security is my field I would like it to be more approachable and not so crammed at the end of the course. Embedding these videos as clear explanations would make the section a lot better in my opinion.

**Comment by chauff** [comment]
Thanks!
