### ISSUE TITLE
Assignment 1, Exercise 1.1: abc.net.au/news/sport/ is now HTTPS

### ISSUE THREAD

**Issue by MaxVanDeursen** [chauff/Web-Teaching#56]
I noticed that [abc.net.au/news/sport/](the abc.net.au website) now uses HTTPS instead of HTTP (not sure whether that was the case the previous years, but now it is definitely the case.

As far as I know, `telenet` can therefore not be used to request the HTML of this page, since it cannot set up the SSL connection required.

Correct me if I'm wrong though, but it seems to be somewhat of a problem.

**Comment by chauff** [comment]
Fixed in [this commit](https://github.com/chauff/Web-Teaching/commit/a552c6f6a9befa7b5b5526ac0bb3c5f1630539bc).
