### ISSUE TITLE
Assignment 1 Exercise 1.2/1.3: Bracket notation

### ISSUE THREAD

**Issue by MaxVanDeursen** [chauff/Web-Teaching#58]
In the exercises, I noticed that the `[xyz]` notation is a placeholder notation in these exerises, although this is not explained anywhere. I think that, without explaining this, much students will revert to explicitly typing `[carriage return]` instead of just pressing enter. Might be worth changing this.

**Comment by chauff** [comment]
Thanks. [Fixed](https://github.com/chauff/Web-Teaching/commit/8cda1c72c16ef261aa5b405b6c2fe7d0be6c677d).
