### ISSUE TITLE
Lecture 1 transcript mistake

### ISSUE THREAD

**Issue by 2016Ruben** [chauff/Web-Teaching#66]
In the lecture 1 transcript, I think there was a minor mistake.

In text about the **Status codes**:
"Here, status code 301 Moved Permanently indicates that the resource at http://volkskrant.nl has been moved elsewhere for good. The Location header tells us the new location (http://volkskrant.nl)."

Shouldn't the second address be https://volkskrant.nl?

**Comment by chauff** [comment]
Indeed! Fixed. Thanks.
