### ISSUE TITLE
Lecture 8 CSRF potential issue

### ISSUE THREAD

**Issue by azqa** [chauff/Web-Teaching#68]
In CSRF DIY, clicking the _"Win !!"_ button redirects to the _Profile_ page (with the updated bankAcc and bankRouting values). In this case, the next step:

> "Reload the Profile page and you should now see bank account and bank routing numbers set to 2."

is not required. Is this the desired behavior?

**Comment by chauff** [comment]
Good catch! Thanks. I'll update it.
