### ISSUE TITLE
Lecture 4 Page 27 Typo

### ISSUE THREAD

**Issue by lightingft** [chauff/Web-Teaching#90]
There appears to be a typo on Lecture 4 Slides Page 27.

![image](https://user-images.githubusercontent.com/34982762/48902555-32685b00-ee59-11e8-96d9-a2f1e85a5198.png)

In the demo code this line is actually query["name"] != undefined and the code above (and in the slide) does not give the desired result.

**Comment by chauff** [comment]
Eagle eyes! Well done. This is now fixed in the slides.
