### ISSUE TITLE
Error(?) in Lecture 4 self-check

### ISSUE THREAD

**Issue by NULLx76** [chauff/Web-Teaching#92]
In the self-check of lecture 4 the function is called like this:
```javascript
f(function(n)){
    console.log(n);
}
```

However, the syntax of the first line is incorrect as the function parameters are closed before the anonymous function is opened thus resulting in an `unexpected token ) on line n` error.

I don't know if this is done intentionally and am therefore opening an issue instead of a pull request.

**Comment by chauff** [comment]
Which question are you referring to?

**Comment by NULLx76** [comment]
Question 3 in the self-check of lecture 4. (made a typo in the original issue)

**Comment by chauff** [comment]
Indeed, an error. Fixed. Thanks.
